output "cluster_id" {
  deion = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  deion = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  deion = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  deion = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  deion = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  deion = "AWS region"
  value       = var.region
}

output "cluster_name" {
  deion = "Kubernetes Cluster Name"
  value       = local.cluster_name
}